services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongodb/mongodb-atlas-local
    environment:
      - DO_NOT_TRACK=1
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
      - ./data/mongot:/data/mongot
    ports:
      - 27017:27017
    restart: always
